### ISSUE TITLE
Email Link

### ISSUE THREAD

**Issue by dmkjr** [adamtootle/staff-directory#18]
I see that ```[email-link]``` has been deprecated, however I have ```<a href="mailto:[email]">[email]</a>``` and it's just linking to not the shortcode, but just the text of ```[email]```

Any ideas?

**Comment by TurqDevDesign** [comment]
@dmkjr I cant duplicate the issue, it's linking correctly for me. Can you provide any more information?

**Comment by adamtootle** [comment]
Same here. It's working for me. Can you drop your template in here? Or maybe a link to see where it's happening?

**Comment by dmkjr** [comment]
```
[staff_loop]
<div id="one-person">
<div class="person-photo"><img src="[photo_url]" />
</div>
<div class="person-name">[profile_link target="_self"] [name] [/profile_link]</div>
<div class="person-titre"><h4>[position]</h4></div>
<div class="person-number">Phone: [phone_number]</div>
<div class="person-email">Email: <a href="[email]">[email]</a></div>
</div>
[/staff_loop]
```

**Comment by adamtootle** [comment]
@dmkjr I've tried to recreate this and it appears to be working on this latest release. I'm closing for now. Let me know if you have any other issues related to this.

Also, just an FYI, using `id="one-person"` inside a loop will result in multiple `one-person` ids on the page, which is invalid html.
