### ISSUE TITLE
Template for Profiles

### ISSUE THREAD

**Issue by dmkjr** [adamtootle/staff-directory#22]
@adamtootle @TurqDevDesign 

How's it going guys?  Been awhile.  

I cannot remember the outcome of this, but if I want the individual staff pages to load using a specific template, how do I do that?  Wasn't it by creating a template and titling it something specific?

Thanks,
David

**Comment by adamtootle** [comment]
Create a new template file in your active theme directory and prefix the filename with `single-staff-`. Then go to Staff > Settings in the admin and select the new template file under "Single profile templates".

**Comment by dmkjr** [comment]
Adam - I am using your plugin again on another website.  I have done this,
however it's not appearing as an option in the drop down for changing
single-staff-custom.php from the menu.

Any ideas?
