### ISSUE TITLE
Amending URL Base '/Staff'

### ISSUE THREAD

**Issue by danleedham** [adamtootle/staff-directory#25]
Hello! Not sure if this is the correct forum for this request. Feel free to point me in the direction of some WP / PHP documentation outlining the process if it's not a unique change for the plugin.

I'm wondering how to change the start of the url from "staff". Love the plugin, love what it does but in our specific scenario we want to use the word "stations" (as in Radio, TV stations). 

At this stage I don't mind of the admin side still shows everything as "Staff", I'd just love to get the URL swapped!

**Comment by danleedham** [comment]
So by adding a 'rewrite' into _classes/staff-directory.php_ line 39~ register_post_type `'rewrite' => array('slug' => 'stations'),` I think I can get this to work? I've also noticed some people asking for this on the support forum, so maybe worth making this a variable that can be set in the admin panel on any future release?

**Comment by adamtootle** [comment]
I'll work on getting a way to set this from the admin. And this is the best way to report issues. I don't get much time to look into this anymore, but issues and PRs here are definitely preferred.

**Comment by adamtootle** [comment]
@danleedham if you want to pull that commit in you can test this. Otherwise it'll go out in the next update. That might be a day or two.
