### ISSUE TITLE
Better support for sorting 

### ISSUE THREAD

**Issue by mattyas** [adamtootle/staff-directory#7]
To support orderby custom field (meta_value\* in wordpress) 
Example:
[staff-directory cat=11 template=custom_1 order=asc orderby=meta_value_num meta_key=my_sort_field]

Just forward 'meta_key'
[staff_directory_shortcode.php.txt](https://github.com/adamtootle/staff-directory/files/120303/staff_directory_shortcode.php.txt)

**Comment by marknorgren** [comment]
@adamtootle were you planning on supporting the orderby custom field ?

**Comment by timnolte** [comment]
~~This feature already works.~~

Actually, I'm wrong. What I though was working was actually just me entering them into the system in the order I was expecting.

**Comment by timnolte** [comment]
@mattyas your code does work. Soon as I get a chance I can submit a PR unless you were planning to.

**Comment by timnolte** [comment]
@adamtootle are you accepting PRs? Are you still interested in supporting this plugin or are you in need of someone to take over, or at least assist with maintenance? Let me know. I've settled on using this plugin for a site that I manage so I'd be more than willing to help add features I need myself, like this one.
